params:
  epochs: 1
  batch_size: 32
  no_of_classes: 10
  input_shape: [28,28]
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_data_size: 5000

artifacts:
  artifacts_dir: artifacts
  model_dir: models
  plot_dir: plot
  checkpoint_dir: checkpoints
  model_name: model.h5

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs